baseURL = "https://campgesher.com/"
title = "Camp Gesher"

enableEmoji = true
enableRobotsTXT = true
hrefTargetBlank = true
googleAnalytics = "UA-41397217-1"
disableKinds = ["taxonomy", "taxonomyTerm"]

[imaging]
quality = 95

[[menu.main]]
name = "Donate"
url = "https://canadahelps.org/en/dn/4502"
weight = 0

[[menu.main]]
name = "Reconnect"
parent = "Alumni"
url = "https://facebook.com/campgesher"

[[menu.main]]
name = "Seminars and Camp"
parent = "Register"
url = "https://gesher.campbrainregistration.com/"

[[menu.main]]
name = "Israel Weekend"
parent = "Register"
url = "https://gesher.campbrainregistration.com/"

[[menu.main]]
name = "Labour Day Getaway"
parent = "Register"
url = "https://gesher.campbrainregistration.com/"

[[menu.main]]
name = "Camp Grant"
parent = "Register"
url = "https://jewishtoronto.com/cje/camp"
