baseURL = "https://campgesher.com/"
title = "Camp Gesher"

# googleAnalytics = "UA-123-45"
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[permalinks]
pages = "/:title/"

[[menu.main]]
name = "Donate"
url = "https://canadahelps.org/en/dn/4502"

[[menu.main]]
name = "Reconnect"
parent = "Alumni"
url = "https://facebook.com/campgesher"
